project_name: 'sttr'

builds:
  - main: ''
    goos: ['linux', 'darwin', 'windows']
    goarch: ['386', 'amd64']
    env:
      - CGO_ENABLED=0

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', 'demo', '^test:', 'Merge pull request', 'Merge branch']